### ISSUE TITLE
More OSB specific error messages 

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#104]
Should update the info we present when there is an error, e.g. a better, more OSB specific message than:

---

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

---

Perhaps also for the 404:
http://www.opensourcebrain.org/projects/fff
and error
http://www.opensourcebrain.org/xyz

**Comment by adrianq** [comment]
@pgleeson It can be change [here](https://github.com/OpenSourceBrain/redmine/blob/development/public/404.html) and [here](https://github.com/OpenSourceBrain/redmine/blob/development/public/500.html) I am not sure about what you have in mind. Can you modify the files or let me know what information you would like to show?

**Comment by pgleeson** [comment]
More specific issues should be added with more recent error pages
