### ISSUE TITLE
Server falls down randomly

### ISSUE THREAD

**Issue by adrianq** [OpenSourceBrain/redmine#109]

**Comment by adrianq** [comment]
It seems to be an issue with some Redmine installations although it is not clear how to solve it. It looks like Passenger  is a much [more reliable framework](http://stackoverflow.com/questions/1728978/recommendations-and-differences-between-different-ruby-on-rails-production-web/1729055#1729055). @pgleeson I remembered that the new NeuroML website is based on redmine and it is using Passenger. Obviously it is not comparable with OSB but you are not having these problems,right?

**Comment by pgleeson** [comment]
No, no stability problems on the new NeuroML site as far as I can see...

**Comment by adrianq** [comment]
Closing this as hopefully the server migration will make OSB much more stable
