### ISSUE TITLE
Make a core set of projects with NeuroML v1.8.1 generated files

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#119]
There should be a few well curated OSB projects whose repositories contain a reasonably complete set of NMLv1 files for a cell or network model, for testing purposes.

Note most [neuroConstruct projects in OSB](http://www.opensourcebrain.org/search_custom_field?f[]=43&op[43]=~&v[43][]=neuroConstruct) have nC based morphology files & ChannelML etc. in certain nC specific folder structure, but don't contain a single complete set of NML1 files, as is the case for many NeuroML 2 models.

As requested by @scrook

Some options for these are:

- [x]   https://github.com/OpenSourceBrain/CA1PyramidalCell/tree/master/neuroConstruct/generatedNeuroML
- [x]   https://github.com/OpenSourceBrain/GranCellLayer/tree/master/neuroConstruct/generatedNeuroML
- [x]   https://github.com/OpenSourceBrain/GranuleCell/tree/master/neuroConstruct/generatedNeuroML
- [x]  https://github.com/OpenSourceBrain/VervaekeEtAl-GolgiCellNetwork/tree/master/neuroConstruct/generatedNeuroML
- [x]  https://github.com/OpenSourceBrain/Thalamocortical/tree/master/neuroConstruct/generatedNeuroML
- [x]  https://github.com/OpenSourceBrain/ACnet2/tree/master/neuroConstruct/generatedNeuroML
- [x] https://github.com/OpenSourceBrain/PyloricNetwork/tree/master/neuroConstruct/generatedNeuroML

(boxes will be ticked as they are added)

**Comment by adrianq** [comment]
@pgleeson is this card done? Can we close it?

**Comment by pgleeson** [comment]
@adrianq, let's leave this open for now, I'll look again at this when I try out mapping the Traub model to NMLv2...

**Comment by pgleeson** [comment]
@adrianq I think this is as much as we can do for now with NMLv1 files, so I'll close this. There are unlikely to be many new OSB projects in pure v1.8.1.

@scrook you were asking about the missing synapse files for Thalamocortical. I've added an issue here: https://github.com/OpenSourceBrain/Thalamocortical/issues/2 for this and will look into it when updating the Traub model for v2

**Comment by pgleeson** [comment]
@scrook Synapses added in nml1 format with https://github.com/OpenSourceBrain/Thalamocortical/commit/0618ca13f667eae2c5da7452279ba20fd44accec

**Comment by scrook** [comment]
Thanks @pgleeson! What are the plans for update to v2?

**Comment by pgleeson** [comment]
We're working on updating/curating those at the moment. @RokasSt is working on the model as part of the Google Summer of Code.

Is there any specific metadata you'd like included/updated in the files?

**Comment by scrook** [comment]
The main metadata that we are using is the publication including authors and pubmed id, an appropriate NeuroLex id (or similar ontological reference), and any keywords from the paper or that we add. Also other references such as ModelDB ID and/or OSB.
