### ISSUE TITLE
Remove old "Model Component" views generated from nC projects

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#128]
e.g. http://www.opensourcebrain.org/embedded/l5bpyrcellhayetal2011/index.html 

These need to be generated offline & committed to an svn repo to be updated & are only for nC projects. Best get rid of these & try to replicate all functionality through OSB Explorer

**Comment by adrianq** [comment]
@pgleeson What is the status of this issue? The link in the issue is not working now. Shoud it be working? Is this a bug we have after the server migration?

**Comment by pgleeson** [comment]
No, they don't need to be accessible anymore. OSB 3d explorer provides much nicer views...
