### ISSUE TITLE
Add 3 options to OSB 3D explorer menu for each NeuroML file: view in explorer; view on GitHub; download

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#130]
i.e. there will be an extra sub menu for each of these with the 3 options

![selection_122](https://cloud.githubusercontent.com/assets/1556687/4677879/f9fa3304-55ed-11e4-920a-bd6b9430e7c8.png)

**Comment by souravsingh** [comment]
I would like to work on the issue. How do I start?

**Comment by pgleeson** [comment]
Hi @souravsingh! Unfortunately this issue is a bit redundant now, as the NeuroML code on Github is a bit more accessible now with an updated Model Description widget in the 3D view. 

I see you have commented on an issue here: https://github.com/openworm/muscle_model/issues/36. I'll add some more info there.
