### ISSUE TITLE
Implement continuous testing

### ISSUE THREAD

**Issue by adrianq** [OpenSourceBrain/redmine#132]
It should include
- [ ] Daily testing for OSB and Geppetto
- [ ] Mail on fail

**Comment by adrianq** [comment]
Useful Link: https://github.com/OpenSourceBrain/osb-model-validation/blob/master/utilities/test_all_osb_projects.py

**Comment by adrianq** [comment]
[Non working models in Geppetto](https://github.com/OpenSourceBrain/redmine/blob/integrationTests/lib/tasks/blackListedModels)

Non valid NeuroML models:
- https://raw.githubusercontent.com/OpenSourceBrain/IzhikevichModel/master/NeuroML2/WhichModel.nml
-

**Comment by pgleeson** [comment]
Superseded by Geppetto's own testing and OMV tests on models...
