### ISSUE TITLE
OSB models failing in visualization

### ISSUE THREAD

**Issue by adrianq** [OpenSourceBrain/redmine#135]
- [x] http://opensourcebrain.org/projects/neuromorpho?explorer=https%3A%2F%2Fraw.github.com%2FOpenSourceBrain%2FNeuroMorpho%2Fmaster%2FNeuroML2%2F17.CNG.swc.nml
- [x] http://opensourcebrain.org/projects/neuromorpho?explorer=https%3A%2F%2Fraw.github.com%2FOpenSourceBrain%2FNeuroMorpho%2Fmaster%2FNeuroML2%2Fl22_sphersoma.nml
- [x] The [KA channel on the Gran cell layer model](http://opensourcebrain.org/projects/grancelllayer?explorer=https%253A%252F%252Fraw.github.com%252FOpenSourceBrain%252FGranCellLayer%252Fmaster%252FneuroConstruct%252FgeneratedNeuroML2%252FGolgi_KA_CML.channel.nml)  gives me `Rats! Something went wrong.`
- [x] The [3D Olfactory bulb model](http://www.opensourcebrain.org/projects/acnet2?explorer=https%3A%2F%2Fraw.githubusercontent.com%2Fpgleeson%2Ftestpy%2Fmaster%2Ftestnml%2FManyCells30.nml) takes a very long time.  However the performance for the [same model but with 3 cells instead of 30](http://www.opensourcebrain.org/projects/acnet2?explorer=https%3A%2F%2Fraw.githubusercontent.com%2Fpgleeson%2Ftestpy%2Fmaster%2Ftestnml%2FManyCells3.nml) is very good.

**Comment by adrianq** [comment]
The exception in KA channel on the Gran cell layer model has to do with the org.neuroml.export lib.  It has been fixed in the lib but it won't be fixed in OSB until the export lib is released and added to geppetto maven repo. I leave this issue open to be sure I check it has been fixed once the new version of the export lib is released.

**Comment by pgleeson** [comment]
Both these fairly simple models are giving errors:

http://www.opensourcebrain.org/projects/cerebellum3ddemo?explorer=https%3A%2F%2Fraw.github.com%2FOpenSourceBrain%2FCerebellum3DDemo%2Fmaster%2FNeuroML2%2FCerebellumNoConns.net.nml

The above has no conns this has a few hundred:

http://www.opensourcebrain.org/projects/cerebellum3ddemo?explorer=https%3A%2F%2Fraw.github.com%2FOpenSourceBrain%2FCerebellum3DDemo%2Fmaster%2FNeuroML2%2FCerebellum3DDemo.net.nml

**Comment by pgleeson** [comment]
For the first I get a "Rats..".

![selection_628](https://cloud.githubusercontent.com/assets/1556687/6714020/fba3d774-cd8d-11e4-875b-8fedc759d805.jpg)

Then a view of the network at too expanded a density (or, the cells themselves are too small):

![selection_627](https://cloud.githubusercontent.com/assets/1556687/6714007/e75cee40-cd8d-11e4-880d-516a13f6e9cf.jpg)

It should look something like this:

![selection_192](https://cloud.githubusercontent.com/assets/1556687/6714239/18902ca6-cd8f-11e4-94f3-4383ec8838dd.png)

**Comment by adrianq** [comment]
Fixed in Geppetto. We were not parsing the includes tags of type (```<include></include>```) properly
