### ISSUE TITLE
Content based 3d explorer selector

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/redmine#136]
Currently, the OSB 3d explorer drop down menu contains a list of files (depending on the extension!!) present in the repo. Evidently, we expect to have models organized in a sensible way file-wise (i.e., one file per channel etc). But I think we should aim for content-based menu generation instead of relying on the location of definitions - i.e., it shouldn't matter if there is only a single sausage-like file with all the definitions: we need to be able to index "cells", "synapses", or "channels" anyhow. 

This can be achieved by annotating ComponentType definitions in the NeuroML schema as Cell, Synapse or Channel, or even maintaining a dict of base_type -> [channel | cell | synapse] and having extensions to "inherit" that. The OSB api can then be used to make queries like "extract all channels from this project", etc. 

Then comes the problem of updating the index after each commit. I think we need to set a [github webhook](https://help.github.com/articles/about-webhooks/) to notifiy OSB of changes to the repo.

**Comment by borismarin** [comment]
@pgleeson @adrianq that's the issue I was referring to. Preparsing commited files and storing lists of domain specific entities (i.e. cells, channels, etc) will also be useful for #146 .

**Comment by pgleeson** [comment]
Think this is out of date given current Model definition parsing. Would ideally be nice to be able to look into all *nml files and find cells & channels before opening them, but a well structured project should have individual files for these too...
