### ISSUE TITLE
Customise Geppetto Tutorial

### ISSUE THREAD

**Issue by adrianq** [OpenSourceBrain/redmine#142]
- [ ] Create a repo in OSB with the tutorial component
- [ ]  Cutomise tutorial component
- [ ] Investigate how to deploy the component in Geppetto Repo or somewhere else

**Comment by tarelli** [comment]
I would propose we make the tutorial component configurable so that it doesn't have to be forked.

**Comment by tarelli** [comment]
The tutorial would be configurable with different sections that will be presented to the user optionally depending on the status of the project. 
Is the user logged in? Show this, else that
Is the experiment completed? Show this, else that

**Comment by pgleeson** [comment]
Done...
