### ISSUE TITLE
Add Control Panel for NeuroML models with buttons for summaries etc.

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/redmine#146]
When a channel is selected, we get the "Summary" widget and some plots. I sometimes accidentaly close the summary by pressing escape, and it would be great to have a nice easily accessible button that restored whatever default panes were being viewed.

**Comment by pgleeson** [comment]
A more general solution for this that we spoke about before is if there is a "control panel" specific for the model with buttons for popping up relevant summaries, e.g.

Cell: 
   - summary of cell; 
   - buttons for summaries of each channel present
   - full Geppetto info in widget

Network: 
   - summary of network; 
   - buttons for summaries of each cell present;
   - buttons for summaries of each synapse present;
   - buttons for summaries of each channel present;
   - full Geppetto info in widget

This can of course be a NeuroML specific feature..

**Comment by adrianq** [comment]
Sounds nice. I would also add "connectivity matrix" for network...

Obviously I can implement this in OSB but I think it would be good to have a widget in Geppetto where you can add buttons and link each button to a js bit of code (which will contain Geppetto API commands). What do you think @tarelli ?

**Comment by tarelli** [comment]
@adrianq sounds like the way to go!

**Comment by pgleeson** [comment]
Great. I've updated the title to reflect this. There should probably be a corresponding issue in Geppetto too...

**Comment by adrianq** [comment]
Geppetto issue created here  openworm/org.geppetto#338

**Comment by borismarin** [comment]
@adrianq @pgleeson see https://github.com/openworm/org.geppetto/issues/338
- http://docs.geppetto.org/en/latest/bubarW.html
The menubar widget will be merged into Geppetto soon. Now it's a matter of writing a conf file for OSB, maybe we need a new card for that and have @pgleeson to review?

**Comment by pgleeson** [comment]
Sure. The suggestions in the 2nd comment at the top should form the basis of the conf files generated for NML models of different types. Maybe it's best to edit that as the requirements for the conf file?

**Comment by adrianq** [comment]
Good job @borismarin! :) We have something very cool and a lot of ideas to improve it!

**Comment by pgleeson** [comment]
Great work guys! Thanks for getting this in before the meeting.

**Comment by tarelli** [comment]
I just released a patch for release 0.2.3 of Geppetto, enjoy :)

**Comment by borismarin** [comment]
If you guys commit anything tomorrow I'll get you some drinks in Sardinia,
so you can relax.
