### ISSUE TITLE
Null Pointer on OSB/Geppetto viewer

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/redmine#147]
The [KA channel on the Gran cell layer model](http://opensourcebrain.org/projects/grancelllayer?explorer=https%253A%252F%252Fraw.github.com%252FOpenSourceBrain%252FGranCellLayer%252Fmaster%252FneuroConstruct%252FgeneratedNeuroML2%252FGolgi_KA_CML.channel.nml)  gives me `Rats! Something went wrong.`

**Comment by adrianq** [comment]
Move to #135
