### ISSUE TITLE
Drawing synaptic connections

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/redmine#149]
The 3d viewer should honor NeuroML's pre/post fractionAlong attributes, which specify from/to which connection "line" should be drawn in the context of a "compartment" (e.g. from 3/4 of the length of cylinder "pre"  to the middle of cylinder "post").

**Comment by adrianq** [comment]
Although it is a domain specific development it should be in Geppetto repo because it is something that eventually will be part of the Geppetto platform. Closing this one and reopening the Geppetto issue
