### ISSUE TITLE
Check adding of new tags to projects

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#150]
Currently there are issues with adding new tags to projects on the main project page:

![selection_166](https://cloud.githubusercontent.com/assets/1556687/6284765/ebd543d4-b8eb-11e4-9546-88097cd3740d.png)

The tag does not appear when the + button is pushed, only when the page is reloaded.

Also, the suggestions as you type of existing tags do not appear.

**Comment by adrianq** [comment]
@pgleeson working now! If you have a chance, give it a try and let me know if it is working for you too!

**Comment by pgleeson** [comment]
Yes, works for me!
