### ISSUE TITLE
Add Neurolex id nifext_49 as Neocortex pyramidal layer 2/3 cell

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#151]
See: http://neurolex.org/wiki/Category:Neocortex_pyramidal_layer_2-3_cell, http://www.opensourcebrain.org/projects/l23dendriticspikes

Currently it's listed as Neocortex uncharacterized cell. Couldn't find where these values are set in the code.

**Comment by adrianq** [comment]
@pgleeson this information is retrieved from the neuroelectro webservice. The problem (see screenshot below) is that we are getting two records for this neurolex_id.

![screenshot from 2015-04-07 17 02 34](https://cloud.githubusercontent.com/assets/6850223/7027619/580b3542-dd48-11e4-85d5-3c761832cc99.png)

 In OSB by default I am reading the first record. Shall we report this as an issue to the neuroelectro people?

**Comment by pgleeson** [comment]
Easiest way to report that is probably just to mention @stripathy and @rgerkin here...

**Comment by stripathy** [comment]
I just fixed this by removing the neurolex id from the neuron type "neocortex uncharacterized cell" from the neuroelectro database. 

So now the only neuron type with nlex_id = "nifext_49" is the L2/3 cell, which is the right behavior.

**Comment by pgleeson** [comment]
Thanks for this @stripathy!
