### ISSUE TITLE
Replace Geppetto asterisk with OSB logo

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#157]
When the 3D model is loading, it would be good to have the OSB logo rotating instead of the Geppetto logo.

Also, some of the warning texts refer to Geppetto. It would be great if these could be customised for OSB.

**Comment by borismarin** [comment]
We already have an OSB icon in the [gepeetto incon bundle](http://rawgit.com/borismarin/org.geppetto.frontend.icons/master/gpt/gpt-icons-preview.html). Not sure the spinning asterisk comes from there, but if that is the case this might be a low hanging fruit.

**Comment by pgleeson** [comment]
Done... (but would still prefer coloured image of logo rather than orange font based circle...)
