### ISSUE TITLE
Can't load ACNet2 [medium net] on chrome (OSX)

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/redmine#159]
![acdead_chrome](https://cloud.githubusercontent.com/assets/3452783/6901129/25b43238-d703-11e4-848b-15a8c89701da.png)

Getting a "Rats!", as well as a dead tab.
It seems to work on Safari, though it takes forever to load.

**Comment by adrianq** [comment]
@borismarin There was a bug in the info extractor (org.neuroml.export) when extracting information for a gate. (As you can see the model has been properly loaded. It can be seen in the background. However when asking for the model tree it fails and throws an error.) I fixed it a month ago but it hasn't been released in Geppetto yet. Hopefully it is going to be there for the next release this month.

Regarding the time it takes to load the model, it is absolutely true it takes too much. Investigating a little bit, most of the time is consumed parsing the neuroml inclusions and sending the data from the server to the client. We are already working on this in many different ways in Geppetto.

I will add this model and others as a QUnit Test (openworm/org.geppetto#374) so we can have an eye on it
