### ISSUE TITLE
Priorities before OSB 2015 meeting

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#160]
- [x] Basic Replay of simulations run in NEURON (@tarelli, @adrianq)
   
    Demo for meeting - not publicly accessible
    Ideally usable by developer on own laptops, etc.

- [x] Control panel/menus (@borismarin, @adrianq)

     Basic functions: for network get list of cells, channels, connectivity options
     See https://github.com/OpenSourceBrain/redmine/issues/146

- [x] Core set of projects (re)tested & included in Geppetto tests (@pgleeson)

    Might be good to focus on hippocampal models:
      CA1 pyramidal
      OLM model (Francis skinner)
      Poirazi CA1 cell 2003
      Pyka [PAM](https://bitbucket.org/rub-hippo/parametric-anatomical-modeling)
      Kopell [Gamma/theta rhythms](https://senselab.med.yale.edu/ModelDB/ShowModel.cshtml?model=13842)

- [x] Minor points that would be good to get done (@adrianq)

    https://github.com/OpenSourceBrain/redmine/issues/155
    https://github.com/OpenSourceBrain/redmine/issues/152

- [x] Move to Amazon (@adrianq)

  https://github.com/OpenSourceBrain/redmine/issues/165

- [x] Updates to Geppetto/OSB visualiser (@tarelli and others)

     *Essential:*
     Error in display of cell positions https://github.com/openworm/org.geppetto/issues/388 

     *Would improve user experience/make it look more scientific*
     Add display of time global variable & scale bar on x axis of plots https://github.com/openworm/org.geppetto/issues/331
     Add attribute to Geppetto to optionally specify what to load https://github.com/openworm/org.geppetto/issues/366

**Comment by adrianq** [comment]
Closing this one. Finally we did it guys :) Thank you all for the big effort! Hopefully I will be releasing in a couple of hours. I will let you know.
