### ISSUE TITLE
Send a welcome email when new users are approved on OSB

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#167]
A basic confirmation is currently sent, but it would be good to make this easier to update & contain current link to help docs, galleries, themes, [contribute page](https://github.com/OpenSourceBrain/Contribute/issues) etc.

**Comment by adrianq** [comment]
@pgleeson I have create [a first draft](https://github.com/OpenSourceBrain/redmine/blob/development/app/views/mailer/account_activated.html.erb) for the welcome email with some links and information.  Can you update/modify it and close the card?

**Comment by adrianq** [comment]
Btw, if you want to test it in your laptop. The mail content appears in your console in html when you activate a user.

**Comment by adrianq** [comment]
@pgleeson I am releasing tomorrow just in case you would like to change/add anything...

**Comment by pgleeson** [comment]
Tried this locally, getting an error related to the recaptcha public key...

**Comment by pgleeson** [comment]
Asked someone who recently registered on OSB & they didn't receive any conf mail.

**Comment by adrianq** [comment]
Locally you have to access using 127.0.0.1, the recaptcha won't work for localhost. The mail is being sent but it sometimes goes into the spam folder as we are not using a proper mail server. Will have a look at this and see if I can install something for this release.

**Comment by adrianq** [comment]
Finally I couldn't install anything for this release. Amazon provides a SMTP server but I have to ask for activation. Hopefully it will be ready for next release

**Comment by pgleeson** [comment]
@mattearnshaw, can you check the links on your confirmation mail, and if everything looks good, close this issue?

**Comment by mattearnshaw** [comment]
all works fine
