### ISSUE TITLE
Delete old help projects in OSB

### ISSUE THREAD

**Issue by adrianq** [OpenSourceBrain/redmine#168]

**Comment by adrianq** [comment]
@pgleeson if it is ok with you I am going to delete the old help projects. Currently they are not accessible as I created redirection for all of them to the new documentation page. I was keeping them just in case we would like to use the content but I think we have been using the new doc for some months so all the content should be migrated.

**Comment by pgleeson** [comment]
Sounds reasonable. Were there repos associated with these? 

It would be good to list at least names of these old projects here (& ideally links to repos) for future reference. 

Best not delete these until this https://github.com/OpenSourceBrain/redmine/issues/188 is sorted.

**Comment by adrianq** [comment]
@pgleeson No repos associated to any project

These are the old help projects and the redirection to the new documentation. I have deleted all of them but I have kept the redirection in case someone/something is pointing to them:

http://opensourcebrain.org/projects/gettingstarted/ => http://opensourcebrain.org/docs#Getting_Started
http://opensourcebrain.org/projects/gitintro/ =>http://opensourcebrain.org/docs/Help/Some_Extra_Information#Introduction_to_Source_Control
http://opensourcebrain.org/projects/feedback/ => http://opensourcebrain.org/docs#How_To_Contact_Us
http://opensourcebrain.org/projects/neuroinformatics/ => http://opensourcebrain.org/docs#Interaction_With_Other_Neuroinformatics_Resources
 http://opensourcebrain.org/projects/simulators/ => http://opensourcebrain.org/docs#Simulators
http://opensourcebrain.org/projects/testprojecu/ => http://opensourcebrain.org/docs#Creating_Your_Own_Project
http://opensourcebrain.org/projects/neuroconstructprojects/ => http://opensourcebrain.org/docs#Using_Neuro_Construct_Based_Projects

These are some other redirections. They are not projects but they used to contain some sort of documentation:
match 'themes', :to => redirect('/docs/Research_Themes')
match 'guides', :to => redirect('/docs')
match 'projects/informationOSB', :to => redirect('/docs')

I have deleted the projects from prod but they can still be found in dev and in the db backup that can be found both in prod and dev.

**Comment by pgleeson** [comment]
Great, thanks!
