### ISSUE TITLE
Check update of local copies of repositories on OSB AWS server

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#171]
Mirrored repositories, used for osb explorer menu & these pages:
http://www.opensourcebrain.org/projects/weileretal08-laminarcortex/repository

don't get updated automatically on new commits to itHub repos:
https://github.com/OpenSourceBrain/WeilerEtAl08-LaminarCortex/commits/master

**Comment by adrianq** [comment]
@pgleeson Finally, it was a problem due to permissions in the folder. It looks good to me but can you please check your latest changes can be seen in the repository tab in OSB? I was not able to test it with bitbucket as I don't have permissions in the repositories. Can you check it as well?

**Comment by pgleeson** [comment]
Looks good to me
