### ISSUE TITLE
Put wiki info on separate page & update info

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#178]
Info on making a wiki here (http://www.opensourcebrain.org/docs#Creating_Your_Own_Project) might be better on its own page & the new project page concentrating on how easy it is to create a new OSB project.

Wiki info should be checked, e.g. Link to an Issue & Link to a Commit not relevant/working...

**Comment by adrianq** [comment]
I have created a wiki web  and extract the information from the 'creating your own project' web. @pgleeson I am not sure what you consider relevant in the wiki page. I am moving this card to test, once you clean it up and you are happy with the content, please move it to done

**Comment by pgleeson** [comment]
Have updated http://www.opensourcebrain.org/docs#Write_Your_Project_Documentation.
