### ISSUE TITLE
3D explorer links are incorrect when navigating from activity, issues, wiki, or files

### ISSUE THREAD

**Issue by JustasB** [OpenSourceBrain/redmine#179]
3D explorer does not show up when navigating from the model's activity, issues, wiki, or files tabs. Works correctly from overview and repository tabs.

Steps to repro:

1) Go to http://www.opensourcebrain.org/projects/thalamocortical
2) Click on activity tab (http://www.opensourcebrain.org/projects/thalamocortical/activity)
3) Click 3D explorer > Cells > first one
Expected: explorer window shows up
Actual: Stays on page

Also happens when the same steps are taken from the issues, wiki, or files tabs. Navigating from those tabs appears to generate incorrect url.

Expected URL: 
http://www.opensourcebrain.org/projects/thalamocortical?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FThalamocortical%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FL23PyrFRB_varInit.cell.nml

Actual URL: 
http://www.opensourcebrain.org/projects/thalamocortical/activity?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FThalamocortical%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FL23PyrFRB_varInit.cell.nml

**Comment by adrianq** [comment]
Thanks @JustasB! Fixed it in development, next week will be in live version,
