### ISSUE TITLE
 Improved cell info view

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#192]
Some things can be done to improve the view of "Cell info" when that button is presses in the control panel:

![selection_720](https://cloud.githubusercontent.com/assets/1556687/9389762/979fc318-4764-11e5-800a-b6ab6fb0108b.jpg)

- [x] Make the widget larger by default; ensure all fields on left can be seen (Number of..?)
- [x] Ensure the contents of the notes element is shown first, followed by num of segment/segment groups
- [x] Give widget better title, e.g. Information on cell; xx
- [ ] Have Channel density entries collapsed by default, so list of all channels presnet can be seen quickly

**Comment by adrianq** [comment]
The last task about the channel density requires some work as we need to define a way to identify this kind of nodes in the export library.

**Comment by pgleeson** [comment]
See https://github.com/OpenSourceBrain/redmine/issues/214
