### ISSUE TITLE
Check cell info button when *.cell.nml file is shown

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#193]
Why is it, e.g. [here](http://opensourcebrain.org/projects/acnet2?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FACnet2%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2Fpyr_4_sym.cell.nml) when a cell is shown (i.e. viewing a *.cell.nml file) and the Cell info button is pressed, that the info for ion chans etc. is shown:

![selection_717](https://cloud.githubusercontent.com/assets/1556687/9389917/9ee58dbe-4765-11e5-9f17-c87ff7be2e37.jpg)

**Comment by adrianq** [comment]
This is the information currently displayed (I have collapsed the folders in the widget so we can see everything):
![screenshot from 2015-09-16 15 35 10](https://cloud.githubusercontent.com/assets/6850223/9907779/992113a2-5c88-11e5-83c2-a611e9668b39.png)

It is the information extracted from the nml model in the InfoWriter as you requested and @borismarin implemented. I think there is nothing wrong in it. If we want to display sth different we can open an issue in org.neuroml.export repo.

**Comment by pgleeson** [comment]
Ok. Could you also change the title on this (and other widgets) to replace TreeVisualiser... with a more relevant title, e.g. Properties of cell: pyr_4_sym

**Comment by adrianq** [comment]
I have already changed [the title for all the widgets](https://github.com/OpenSourceBrain/redmine/blob/development/public/geppetto/scripts/utils/osbCellUtils.js#L10) It is in development, I will release again on Wednesday or Thursday

**Comment by pgleeson** [comment]
Thanks!
