### ISSUE TITLE
Overhaul of OSB 3D visualiser channel property information/plotting

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#200]
Needs to work for any ion channel model in nml2, not just with known HH form of activation variables.

Probably will require use of initial version of @borismarin's org.lemsml.model...

**Comment by adrianq** [comment]
Moving this card to the ideas. When @borismarin is done with the new model we can start working on it.  I have added a validation so that we don't get an error when we try to deal with non HH.

**Comment by pgleeson** [comment]
Replaced by https://github.com/OpenSourceBrain/redmine/issues/262
