### ISSUE TITLE
Enable 3D view of cells with lines for neurites as opposed to 3D segments

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#201]
This option is present in neuroConstruct, to show all segments in 3D; just soma in 3D and rest as lines; all in lines:

![selection_726](https://cloud.githubusercontent.com/assets/1556687/9768649/ef48b2ce-571c-11e5-86ff-da7cd1c3db8b.jpg)

The "show as lines" option is much lighter on graphics memory in nC. 

This would be great to get into OSB 3D explorer (option to be set by command line, or preselected depending on size of model) as it would most likely allow much larger cell & network models to be displayed.

@tarelli, where is a good place for this in https://github.com/openworm/org.geppetto.frontend? This might be a fairly straightforward task for a volunteer with some three.js skills.

Setting of resolution of 3D segment display (from 6 faces for cylinders) would also be nice, for when a graphics card will support higher resolution:

![selection_729](https://cloud.githubusercontent.com/assets/1556687/9768798/fa60a54e-571d-11e5-99d4-40d802dad7dd.jpg)

**Comment by adrianq** [comment]
@tarelli is working on this already. There is a [card in Geppetto](https://github.com/openworm/org.geppetto.frontend/issues/343). Once done we can think about a proper way to integrate it in OSB. Probably a button in the control panel...

**Comment by pgleeson** [comment]
Implemented in Geppetto...

**Comment by pgleeson** [comment]
Reopening this and pointing @mattearnshaw at it. It would be good to get the 3rd option (middle cell above): soma solid, neurites shown as lines. Good for displaying large networks and seeing the location of the somas

**Comment by pgleeson** [comment]
Current implementation covers this all quite well
