### ISSUE TITLE
Ease of going from cell info widget to channel info

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#214]
E.g. if a cell info widget is shown, have clickable link from channel text tags to open channel info widget

**Comment by adrianq** [comment]
At the moment, what Geppetto provides for this is a right-click context menu. Is this enough or we are thinking about something different? The cell widget is generated from the information provided by the export library. If we want to create this feature we would have to identify this kind of channels and match it to a property (maybe the domainType although I am not sure about this)

**Comment by pgleeson** [comment]
I'm starting to think there is a need for a "Cell Overview" HTML view similar to the Model Overview HTML view:

![selection_069](https://cloud.githubusercontent.com/assets/1556687/13924382/0c12e8dc-ef7c-11e5-9a47-f3d694001061.png)

This would allow display of a summary of the cell:

- Description
- Link to original NML version
- Summaries of channel densities incl hyperlinks for channels
- Link to current Dat widget view of cell for "full info"

**Comment by pgleeson** [comment]
Some inspiration for this:

http://mariannebezaire.com/ca1_graphic/mymodel.html

**Comment by pgleeson** [comment]
This is fixed in latest dev branch. New issues will be open for specific tweaks
