### ISSUE TITLE
Button for info on inputs

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#217]

**Comment by borismarin** [comment]
-[ ] add domain type for inputs (neuroml model interpreter)
-[ ] proceed analogously to "channel info" button

**Comment by borismarin** [comment]
-[ ] add domain type to inputs (neuroml model interpeter)
-[ ] adapt the "channel info" button from button bar

**Comment by pgleeson** [comment]
Or even better have a separate Inputs button
