### ISSUE TITLE
Example projects/experiments for non logged in users 

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#219]
So new users can see/replay some curated projects without logging in/setting up own experiments

Examples to add:
- [ ] Acnet1
- [ ] One detailed cell model (Hay et al?)
- [ ] Pyloric
- [ ] Izhikevich

**Comment by adrianq** [comment]
Updated list as discussed with @pgleeson:
- [ ] CA1
- [ ] Acnet2
- [ ] HH
- [ ] Izhikevich
- [ ] One of the L23 Cell
