### ISSUE TITLE
Perspectives - Network / Cell / Channel

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/redmine#222]
We could potentially improve visualisation by having contextual (as in network/cell/channel) widgets / 3d view, i.e. the set of things displayed in the screen (buttons, widgets, 3d) depends on whatever is selected.
Related to https://github.com/openworm/org.geppetto.frontend/issues/279

Not sure how we would "select" a network or channel from the 3d view (or even what to see in for the channel case), though. 
@pgleeson, @adrianq, @tarelli

**Comment by adrianq** [comment]
I think this is a good idea but as you say it is difficult to understand how we can select a network or a channel. The interesting thing about this approach imho is the fact that we will reduce the number of buttons and toolbars. Some questions come to my mind: How to make clear to the user the context where we he is working on? How to change from one context to another? Something much more intelligent than the current control panel would be needed. Definitively a lot of design is needed for this

**Comment by pgleeson** [comment]
Specific suggestions/issues for updates to current display can be added...
