### ISSUE TITLE
Add Summary Information button to OSB Control panel

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#223]
Add a button to the OSB Control Panel to give a "one page summary" of the information related to the currently visualised model. Should ideally be a single well formatted (html?) page (not tree of expandable info) with:

- [ ] Links to the original NeuroML files on Github on which the visualised model was based (open in new window)
- [ ] Current status of the model (persisted, modified from etc.)
- [ ] Summary of the contents of the model, lists of cells, populations, channels, inputs with hyperlinks to open the widget for that element

Something along these lines was mentioned here: https://github.com/OpenSourceBrain/redmine/issues/146

**Comment by adrianq** [comment]
@pgleeson Is this a new widget? If so, what is the purpose of this widget? rendering html? The information is going to be retrieved from the export library? Is this a new module/writer in the export library? Is this information going to be part of the ModelTree in Geppetto (as the Summary currently) or is it going to be fetched just for this widget? I have seen @borismarin and myself are in charge of this task but if we have to implement something new in the Geppetto side maybe it is a good idea to discuss this with @tarelli. Btw, I have seen a lot of issues about buttons and control panels but maybe it would be a good idea to draw a mockup about how it  should look. Don't get me wrong it sounds like a good idea but it is difficult to understand the whole picture with individuals issues

**Comment by adrianq** [comment]
This task is currently addressed [in this issue in Geppeto](https://github.com/openworm/org.geppetto.model.neuroml/issues/83). There is a draft at the moment for this summary but the whole thing won't be done until we finish with the instance/type refactor.

**Comment by adrianq** [comment]
Done! It will be live in OSB as soon as we release the latest of Geppetto into OSB. If we find something unexpected we can open individual cards to deal with the issues.
