### ISSUE TITLE
Tests for Geppetto type instance refactoring

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#227]
A list of OSB projects etc. which currently are difficult/slow to view and which will be improved with the type/instance refactor (and line view) in Geppetto...
Also some user interaction scenarios that need to be enabled.
### Very simple (1 compartment)
- [x] HH Cell single compartment: http://www.opensourcebrain.org/projects/hodgkin-huxley-tutorial?explorer=https%3A%2F%2Fraw.githubusercontent.com%2Fopenworm%2Fhodgkin_huxley_tutorial%2Fmaster%2FTutorial%2FSource%2FHHCellNetwork.net.nml
- [x] 5 HH like cells: http://www.opensourcebrain.org/projects/pospischiletal2008?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FPospischilEtAl2008%2Fmaster%2FNeuroML2%2FFiveCells.net.nml
- [x] OpenWorm muscle cell http://www.opensourcebrain.org/projects/muscle_model?explorer=https%3A%2F%2Fraw.githubusercontent.com%2Fopenworm%2Fmuscle_model%2Fmaster%2FNeuroML2%2FNeuronMuscle.net.nml
- [x] 5 Izhikevich cells: http://www.opensourcebrain.org/projects/izhikevichmodel?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FIzhikevichModel%2Fmaster%2FNeuroML2%2FFiveCells.net.nml
- [x] Granule cell layer **network** http://www.opensourcebrain.org/projects/grancelllayer?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FGranCellLayer%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FGranCellLayer.net.nml
-  [ ] Pyloric **network** http://www.opensourcebrain.org/projects/pyloricnetwork?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FPyloricNetwork%2Fmaster%2FNeuroML2%2FFig3.net.nml
### Simple (10 compartments)

**Acnet**
- [x] 60 cell **network**: http://www.opensourcebrain.org/projects/acnet2?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FACnet2%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FMediumNet.net.nml
- [x] 3000 cells No connections: http://www.opensourcebrain.org/projects/acnet2?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FACnet2%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FLargeNet.net.nml
### Medium (50-100 compartments)

**Traub et al 2005**
- [x] 60 cells no connections
  http://www.opensourcebrain.org/projects/thalamocortical?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FThalamocortical%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FLayer23_NoConns.net.nml
- [x] 60 cell **network** & connections
  http://www.opensourcebrain.org/projects/thalamocortical?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FThalamocortical%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FLayer23.net.nml 
- [x] 300 cell **network** & connections
  http://www.opensourcebrain.org/projects/thalamocortical?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FThalamocortical%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FLargeConns.net.nml
### Complex  (100 - 1000 compartments)
- [x] Celegans full **network** (302 different cells bu 6000 connections) http://opensourcebrain.org/projects/celegans?explorer=https%3A%2F%2Fraw.githubusercontent.com%2Fopenworm%2FCElegansNeuroML%2Fmaster%2FCElegans%2FgeneratedNeuroML2%2FCElegans.net.nml
- [ ] Multiple examples here: https://github.com/OpenSourceBrain/OpenCortex/tree/master/examples
### Very complex (>1000 compartments)
- [x] L5b Hay et al:
  http://www.opensourcebrain.org/projects/l5bpyrcellhayetal2011?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FL5bPyrCellHayEtAl2011%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FTestL5PC.net.nml
- [x] Golgi cell:
  http://www.opensourcebrain.org/projects/vervaekeetalgolgicellnetwork?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FVervaekeEtAl-GolgiCellNetwork%252Fmaster%252FNeuroML2%252FGolgi_040408_C1.cell.nml
- [x] CA1 pyramidal
- [x] Blue brain project, 10 detailed cells: http://www.opensourcebrain.org/projects/blue-brain-project-showcase?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FBlueBrainProjectShowcase%2Fmaster%2FNMC%2FNeuroML2%2FCellTypesPerLayer.net.nml
- [ ]  49 detailed cells from the Allen Institute http://www.opensourcebrain.org/projects/alleninstituteneuroml?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FAllenInstituteNeuroML%2Fmaster%2FCellTypesDatabase%2Fmodels%2FNeuroML2%2FManyCells.net.nml

**Comment by pgleeson** [comment]
@tarelli @adrianq Updated. Happy testing!

**Comment by adrianq** [comment]
There are some issues with a few of them. I will keep the card opened until I check what is going on with them...

**Comment by adrianq** [comment]
There was a problem with the 5 HH Model about how we were solving the includes. It is solved in dev not yet in OSB.

**Comment by adrianq** [comment]
Finally the problem with the pyloric model has to do with the projections. We need to parse the different projections in Geppetto (electricalConnection, continuousConnection, etc). I will open another card for that and close  this one. As the rest of the models have been tested...

**Comment by pgleeson** [comment]
Closing this and individual issues can be opened for specific projects
