### ISSUE TITLE
Page in OSB docs on current status of running simulations

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#228]
Can be brief for now, but should state: overall goals/limitations; what can be done at present; simulators available; overview of workflow; example projects to try; required console interaction; future plans. Pointers to Geppetto docs for more info

**Comment by pgleeson** [comment]
Console commands suggested here:
https://github.com/openworm/org.geppetto/issues/445

**Comment by mattearnshaw** [comment]
some minimal info now exists opensourcebrain.org/docs#Running_Simulations_on_OSB
