### ISSUE TITLE
Visualisation displays no cells (but they exist in the background) for some networks

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#233]
This may be related to the switch to lines view. For the [MiglioreEtAl14_OlfactoryBulb3D](https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D) example, PartialBulb_3MTCells.net.nml displays file, but PartialBulb_30MTCells.net.nml (identical layout but just 10x larger) displays nothing, but cell info seems to be there in Geppetto. 

@adrianq was looking into this yesterday, as it was happening with https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/master/CellTypesDatabase/models/NeuroML2/CellTypesPerLayer.net.nml too. @tarelli if you get a chance to have  look at this this morning it would be great, I'm trying to get some screenshots from these models for the OSB poster for SfN.

**Comment by tarelli** [comment]
@pgleeson @adrianq see my other comment about this. I suggest to increase that number in OSB so default lines won't happen for any model. At the same time let's put in a bug the specific models where line visualization doesn't work so we can check what's up with those and for the next release we turn that number into an instance configuration parameter regardless.

**Comment by pgleeson** [comment]
Ok, have done that in local copy (disabled lines by default). Allen cells load fine, but changing to lines displaces all cells to origin...

![selection_767](https://cloud.githubusercontent.com/assets/1556687/10452795/3446259a-719f-11e5-8d12-9e7e85e6cde6.jpg)

goes to:

![selection_766](https://cloud.githubusercontent.com/assets/1556687/10452768/0556e2a6-719f-11e5-82cb-046b70040b8e.jpg)

**Comment by adrianq** [comment]
An issue to solve this problem has been created in Geppetto --> [Here](https://github.com/openworm/org.geppetto.frontend/issues/348)

**Comment by pgleeson** [comment]
The Geppetto issue related to this is closed, but I'm still having issues like this with a local copy of the development branches. Basically any network that is automatically switched to lines view because of size is just not displayed...

**Comment by pgleeson** [comment]
These networks are still showing issues in the live version (not sure it's exactly same problem, but these are large enough that they probably default to lines view):

http://www.opensourcebrain.org/projects/blue-brain-project-showcase?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FBlueBrainProjectShowcase%2Fmaster%2FNMC%2FNeuroML2%2FCellTypesPerLayer.net.nml

http://www.opensourcebrain.org/projects/blue-brain-project-showcase?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FBlueBrainProjectShowcase%2Fmaster%2FNMC%2FNeuroML2%2FCellTypesPerLayer.net.nml

Note: there is also a (possibly different) problem with the Hay et al cell:

http://www.opensourcebrain.org/projects/l5bpyrcellhayetal2011?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FL5bPyrCellHayEtAl2011%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FL5PC.cell.nml

**Comment by pgleeson** [comment]
(2nd link above corrected) Note: result for both of the first 2 is a black empty screen, but a top level object CellTypesPerLayer exists in the console

**Comment by tarelli** [comment]
@pgleeson @adrianq I was able to visualize them switching to tubes and then back to lines with the console, so it should be something small, I will look at it after the instance/type refactoring.
![screen shot 2015-12-08 at 19 25 46](https://cloud.githubusercontent.com/assets/81127/11665884/84b93288-9de1-11e5-8a5e-
058a419b0333.png)

**Comment by pgleeson** [comment]
A slightly different issue with a local copy of the development version:
![selection_043](https://cloud.githubusercontent.com/assets/1556687/12950519/7de414e0-d005-11e5-9c6a-37bc287bf390.png)

**Comment by tarelli** [comment]
@pgleeson the issue is that there are two extra cells right?

**Comment by pgleeson** [comment]
Not really, there should be 10 cells: https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/NMC/NeuroML2/CellTypesPerLayer.net.nml

But they should all be different (they seem to be copies of the first)...

![selection_044](https://cloud.githubusercontent.com/assets/1556687/12951764/c3714978-d00b-11e5-90d7-bac002e5b3ed.png)
