### ISSUE TITLE
Log in not working on Safari

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#237]
As reported by Frederic Lanore and verified on my Mac...

**Comment by pgleeson** [comment]
Sadra here has this too... No feedback that there's anything wrong, just doesn't respond

**Comment by adrianq** [comment]
This [PR](https://github.com/openworm/org.geppetto.frontend/pull/363) should solved the problem. I will release OSB just after Geppetto and double check this problem is fixed.
