### ISSUE TITLE
Check execution of Neuron simulations on live OSB

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#243]
@adrianq, @tarelli I've started a number of simulations this morning and just now and none have successfully finished, they remain queued. Can you have a look and see if Neuron is running correctly on the OSB server?

**Comment by adrianq** [comment]
@pgleeson it is working now. I have rebooted the server. I couldn't see anything in the logs so I assumed it was an out of memory.I will definitively have a look at the persistence and external simulator bundle once we are done with refactor. We need to have sth much more robust
