### ISSUE TITLE
Colour info in population tag in NeuroML should override default population

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#244]
Tasks involved:
- [ ] Extend the geppetto model to specify an optional colour for a VisualType
- [ ] Read the annotation, if it exists, in NeuroML
- [ ] Update the frontend to read the colour

Many networks (e.g. generated by neuroConstruct) have population colour info in annotations in the populations tag, e.g. [here](https://github.com/OpenSourceBrain/ACnet2/blob/master/neuroConstruct/generatedNeuroML2/TwoCell.net.nml). This could be used to override the default colouring of entities in Geppetto and instead of views like this:

![selection_017](https://cloud.githubusercontent.com/assets/1556687/11869228/f1ae64fa-a4b5-11e5-9821-770e6a8642db.png)

it would be more like this:

![selection_018](https://cloud.githubusercontent.com/assets/1556687/11869233/fcb439ec-a4b5-11e5-94b0-33ea1556a9c3.png)

**Comment by pgleeson** [comment]
Looking at @borismarin's chord diagrams, it would be nice to use the same colours for the chords as the colours for the populations in the 3D view. This info can easily be pulled from the [network file](https://github.com/OpenSourceBrain/ACnet2/blob/master/neuroConstruct/generatedNeuroML2/TwoCell.net.nml).

**Comment by borismarin** [comment]
Can do, even though those colours are not perceptually similar -an
important feature when choosing colourmaps (the default one, for 20
categories, has carefully chosen colours). I know @pgleeson does not care
and only wants to have whatever is in neuroml, but there is science behind
visualisation:

See eg

https://mycarta.wordpress.com/2012/05/29/the-rainbow-is-dead-long-live-the-rainbow-series-outline/

https://stanford.edu/~mwaskom/software/seaborn/tutorial/color_palettes.html

http://colorbrewer2.org/

http://jnnnnn.github.io/category-colors-2L-inplace.html

Bottom line : use neuroml colours, but choose those systematically in order
to get decent visualisation.
On 18 Feb 2016 09:35, "Padraig Gleeson" <notifications@github.com> wrote:

Looking at @borismarin <https://github.com/borismarin>'s chord diagrams, it
would be nice to use the same colours for the chords as the colours for the
populations in the 3D view. This info can easily be pulled from the network
file
<https://github.com/OpenSourceBrain/ACnet2/blob/master/neuroConstruct/generatedNeuroML2/TwoCell.net.nml>
.

—
Reply to this email directly or view it on GitHub
<https://github.com/OpenSourceBrain/redmine/issues/244#issuecomment-185626811>
.

**Comment by pgleeson** [comment]
If you're happy to generate a text file with 20+ scientifically chosen hex colours I can add this to nC and pyNeuroML to ensure the populations always get generated with the same sequence of colours. 

Not sure about having the 2 shades of blue as the starting colours though...

**Comment by borismarin** [comment]
Sure, many online tools (see below) can generate that automatically.

The map that starts two s with hades of blue is [one of the default colormaps in d3] (https://github.com/mbostock/d3/wiki/Ordinal-Scales#category20) (20 colour). It has "paired" colours for some reason...

What about this one (12 colours) from colorbrewer: (from [here](http://colorbrewer2.org/?type=qualitative&scheme=Set3&n=12)
["#8dd3c7","#ffffb3","#bebada","#fb8072","#80b1d3","#fdb462","#b3de69","#fccde5","#d9d9d9","#bc80bd","#ccebc5","#ffed6f"]

or this one (20 colours) generated with iwanthue:
["#5790B8","#DAC038","#C85A5A","#5A8A6B","#CA82D3","#856B37","#81DB51","#CBE24A","#B6658B","#C1A650","#E2624A","#CE7A35","#6FB655","#C5C8D2","#CF9980","#DE92EF","#656D6F","#8F8DCA","#CBD898","#6ECFD4"]


http://tools.medialab.sciences-po.fr/iwanthue/index.php
https://bl.ocks.org/mbostock/5577023
http://colorbrewer2.org
https://vis4.net/blog/posts/avoid-equidistant-hsv-colors/

**Comment by mattearnshaw** [comment]
general plan for this is to add a 'Visual Preference' type to the Geppetto model, which we can use in future to persist any user defined aspects of the display; widget positions, camera position, colours etc.

**Comment by mattearnshaw** [comment]
in `0.3.6`
