### ISSUE TITLE
3D explorer shows unable to connect error

### ISSUE THREAD

**Issue by JustasB** [OpenSourceBrain/redmine#245]
Going to

http://opensourcebrain.org/projects/miglioreetal14_olfactorybulb3d?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FMiglioreEtAl14_OlfactoryBulb3D%2Fmaster%2FNeuroML2%2FPartialBulb_5MTCells.net.nml

Shows
![screen shot 2016-01-02 at 3 58 29 pm](https://cloud.githubusercontent.com/assets/10732358/12076487/c79e272a-b169-11e5-9213-2ecdccf9fd0f.png)

**Comment by pgleeson** [comment]
The server required restart & should be fine now @JustasB

**Comment by JustasB** [comment]
It's working
