### ISSUE TITLE
Review Integration with Geppetto

### ISSUE THREAD

**Issue by adrianq** [OpenSourceBrain/redmine#248]
- [x] Remove super types from treevisualiser dialogs
- [x] Make warning dialog about volatile project appears when setting watched variable
- [x] Check changing of value of length of experiment - it gets set as `'1<br>'` when a value of 1 is entered in the Experiment tab
- [x] When a new experiment is added to existing project the dt and length values from the previous experiment should be used, not 0 (note: simulator field also blank...)
- [x] When new experiment added, make this active by default (or ask to switch to it)
- [x] Download links not working: https://github.com/openworm/org.geppetto/issues/446
- [x] Just list names of state variables, as opposed to saying "v 0mV" etc. in type summary
- [x] Show confirmation dialog when run has been successfully submitted to server
- [x] Changing from an open 3D view to another nml file (via OSB 3D explorer menu) not working 
- [ ] When viewing cell with 1 cell region (e.e. hodgkin_huxley_tutorial, with just soma group), select Cell Visual; select Show Visual Groups (right click CellRegion) and the cell (or all network) disappears
- [x] OSB Control panel not appearing when not logged in
- [x] When a network has just one cell, it should be selected from the beginning
- [ ] Ensure Run button is still enabled after failed run, e.g. before project is persisted -> press run -> get warning -> persist -> run button is disabled...
- [ ] When there is only one cell in network and Cell Info or Cell Visual selected, select that cell and show info rather then "There is no cell selected..."
- [ ] When shift/play (stream/display time evolution of graphs) is selected, a widget should be popped up showing the value of t, i.e. time at that moment.
- [ ] Geppetto projects opened from (logged in) home screen shouldn't open in small window on that page but in a new window or ideally, one associated with the OSB project from which it was originally created

**Comment by adrianq** [comment]
cc @pgleeson

**Comment by pgleeson** [comment]
@tarelli @gidili I've got the latest running locally and it's looking good. Adding a number of minor issues here for streamling the workflow. Many OSB specific, but others might impact Geppetto too...

**Comment by pgleeson** [comment]
cc @tarelli

**Comment by pgleeson** [comment]
Most of these issues are now solved or no longer relevant (or have their own issues)...
