### ISSUE TITLE
Have a main entry point for a given OSB project

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/redmine#272]
Have a main entry point for a given OSB project the complete runnable model rather than only showing all files indistinctly. Do this through a configuration file in the repo that will specify what the entry point is.

**Comment by pgleeson** [comment]
This is pretty much done if there is a _osb.yml file in the GH repo, e.g. https://github.com/OpenSourceBrain/ACnet2/blob/master/_osb.yml
