### ISSUE TITLE
Ensure "5 minute intro" to OSB/Geppetto is visible & up to date

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/redmine#273]
The goal is for the document to be then created as an HTML page (see [this](http://opensourcebrain.org/docs#Write_Your_Project_Documentation) for instance) and linked from OSB in a prominent way.

**Comment by pgleeson** [comment]
This is present under the Help tab when a user is logged in, but ideally should be easy to find for non logged in users too via the Help link at the bottom of the page.

**Comment by mattearnshaw** [comment]
now available from the main help, but it's duplicated, so leaving this open to remind me. really the Help tab for logged in users is redundant and should be deleted, and a more prominent link to the main docs added.
