### ISSUE TITLE
Improve cell info workflow for networks with single cell

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/redmine#276]
When there is only one cell in network and Cell Info or Cell Visual selected, select that cell and show info rather then "There is no cell selected..."

**Comment by pgleeson** [comment]
Another for @mattearnshaw...

See for example: http://www.opensourcebrain.org/projects/l5bpyrcellhayetal2011?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FL5bPyrCellHayEtAl2011%252Fmaster%252FneuroConstruct%252FgeneratedNeuroML2%252FTestL5PC.net.nml and press Cell Visual

**Comment by mattearnshaw** [comment]
fixed by https://github.com/OpenSourceBrain/geppetto-osb/commit/b57b056c26a7eb1a54c5d27185b58e7d8c61bb6f, will close this once it is deployed
