### ISSUE TITLE
Disable Explore model button if no NML2 files are found

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#284]
e.g. http://www.opensourcebrain.org/projects/large-scale-visual-short-term-memory-ulloa-and-horwitz-2016

**Comment by mattearnshaw** [comment]
above commit works, but follows the existing pattern of this erb file which is already too ad-hoc, there's about 50 script tags rendered into some pages. need to think about how to refactor this to keep it maintainable
