### ISSUE TITLE
allow git repos with same name

### ISSUE THREAD

**Issue by mattearnshaw** [OpenSourceBrain/redmine#298]
currently everything goes into `~/svnsvn/myGitRepositories` and so redmine won't let you create a project if   there is a name collision

**Comment by pgleeson** [comment]
One solution might be to use the existing ~/svnsvn/myGitRepositories if the repos are hosted at https://github.com/OpenSourceBrain, and make a subfolder (or prepend the folder name) with the organisation name, e.g. 
https://github.com/pgleeson/test -> ~/svnsvn/myGitRepositories/pgleeson/test.
Note though there are already some non github.com/OpenSourceBrain residing repos in ~/svnsvn/myGitRepositories so these would still have to work.
