### ISSUE TITLE
projects.json sometimes malformed

### ISSUE THREAD

**Issue by mattearnshaw** [OpenSourceBrain/redmine#300]
only appears to happen on live (not locally), and in firefox, if the limit > ~50
eg. http://0.0.0.0:3000/projects.json?limit=153
occassionally malformed JSON is returned...

**Comment by pgleeson** [comment]
@ramcdougal this is the file for pulling the ModelDB info from OSB: https://github.com/OpenSourceBrain/OSB_API/blob/master/python/examples/CheckModelDB.py

However it's broken at present due to this unresolved issue...

**Comment by mattearnshaw** [comment]
cc @ramcdougal, `CheckModelDB.py` (see above) now works

travis is still failing but for unrelated reasons

**Comment by pgleeson** [comment]
Travis tests passing now.
