### ISSUE TITLE
h5 support

### ISSUE THREAD

**Issue by mattearnshaw** [OpenSourceBrain/redmine#306]
initial problem is if `<network>` id and `<neuroml>` id are different, then the current strategy of matching regex on the raw h5 to get the `<neuroml>` id ([here](https://github.com/OpenSourceBrain/redmine/blob/frontend-refactor/app/helpers/projects_helper.rb#L402))  means geppetto gets the wrong ID. ruby support for hdf5 seems quite limited but we will likely need it eventually anyway.

**Comment by pgleeson** [comment]
Moving this to broader issue for H5 file viewing: https://github.com/OpenSourceBrain/geppetto-osb/issues/306
