### ISSUE TITLE
basic mobile compatibility

### ISSUE THREAD

**Issue by mattearnshaw** [OpenSourceBrain/redmine#310]
site is a bit broken on mobile – should at least make sure front page displays well, viewport is correct, etc.

- [x] front page displays correctly
- [ ] project pages
- [ ] geppetto iframe viewport/scaling or message "not supported on mobile"

**Comment by mattearnshaw** [comment]
front page resolved at https://github.com/OpenSourceBrain/redmine/commit/85be8c03651c9fb1ad34a2e47419c3f089cd5bb5

**Comment by pgleeson** [comment]
Adequate for now... Desktop can always be requested...
