### ISSUE TITLE
Make it clear that the project URL will be long if the title of the project is long

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#325]
e.g. http://www.opensourcebrain.org/projects/tcrelay-neuron-morris-lecar-model-with-added-t-h-and-ahp-currents-zeldenrust-et-al-2013

On New Project page, show a field with full URL at the same time as project name...

**Comment by sanjayankur31** [comment]
What do we need done here? The identifier field already populates while the project name is being entered:

![new-project-identifier](https://user-images.githubusercontent.com/102575/78540844-a73cfa80-77ec-11ea-81ae-87b73e84492d.png)

**Comment by pgleeson** [comment]
Perhaps below identifier have a preview of the project URL (uneditable), e.g.

https://www.opensourcebrain.org/projects/a-very-long-project-name-etc-etc-etc-etc-etc-etc
