### ISSUE TITLE
Disable reCaptcha if redmine is installed locally with docker-compose for testing

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#326]
So that test users can be registered.

@zsinnema found this also.  @sanjayankur31 will look into this

**Comment by sanjayankur31** [comment]
@pgleeson  @zsinnema: could you give me steps to reproduce this issue when you have a minute please?

**Comment by pgleeson** [comment]
Go to http://localhost:10083/account/register, try to register and you'll get an error with recaptcha:
<img width="927" alt="Screenshot 2020-05-19 at 14 09 14" src="https://user-images.githubusercontent.com/1556687/82330193-6aaf1200-99da-11ea-8cfd-4711394c5e39.png">

So you could check is localhost is in the hostname, and if so, don't show the recaptch, but let anyone register (for testing).

**Comment by sanjayankur31** [comment]
Found an easier workaround:

https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do

There are keys mentioned there that will allow all verifications to proceed. Works well for localhost:

```
Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
```

Closing.

**Comment by pgleeson** [comment]
Great, thanks!
