### ISSUE TITLE
Update to newest redmine and ruby releases

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/redmine#331]
This uses quite an old version of redmine, and ruby 2.3.0 which went EOL more than a year ago (and is very hard to find and use nowadays!).

The docker-redmine project has also moved on, so our docker image will also need to be updated accordingly.

**Comment by pgleeson** [comment]
Also specific libraries will have to be updated, e.g. https://github.com/OpenSourceBrain/redmine/pull/307

**Comment by sanjayankur31** [comment]
The current OSB deployment that uses redmine is being phased out in favour of OSBv2. The new version does not use redmine at all. Therefore, we will not spend the effort to update redmine/ruby to new versions. Rather, we'll keep it in maintenance mode where any issues will be patched/hotfixed.
