### ISSUE TITLE
When a password is changed, it changes in redmine database but not geppetto database

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#333]
Due to the email confirmation getting sent (and failing) between setting redmine pw and geppetto pw. Related to #332.

If this happens a user can log in with the new pw, see their user/project pages, but will see "Guest" (the guest/anonymous geppetto account) on the right at their "Your models" page:

<img width="998" alt="Screenshot 2020-03-25 at 11 21 11" src="https://user-images.githubusercontent.com/1556687/77531446-d6697880-6e8a-11ea-889c-e05e538a4271.png">

Temp fix for any user having this is to set the pw field in geppetto db to hashed_password value from redmine db.

**Comment by sanjayankur31** [comment]
A hotfix for this could be to run the Geppetto synchronisation code before the code that sends out the e-mail? I.e. move lines 88-89 here after the Geppetto update:

https://github.com/OpenSourceBrain/redmine/blob/master/app/controllers/account_controller.rb#L87

**Comment by sanjayankur31** [comment]
When #332 is fixed, this will be fixed too.
