### ISSUE TITLE
Create "Run this model on NSG portal" option

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#72]
General idea:

If a repo has a NEURON sub folder (i.e. contains an executable NEURON model), add a custom filed on OSB projects for Main_NEURON_hoc_file, and if present on a project add a button "Run this model on NSG portal" to the main project page, which retrieves the NEURON folder, zips it in a format that's ready for submission to 
http://www.nsgportal.org. 

In first version user needs to download zip & log in to NSG & upload zip & set running but this could be automated over time

Could be extended for other simulators over time.

**Comment by adrianq** [comment]
Closing this as we will be doing something much better in the following months...
