### ISSUE TITLE
Enable visualising of SWC files in OSB Explorer e.g. for NeuroMorpho

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#91]
Steps required:

Update https://github.com/pgleeson/Cvapp-NeuroMorpho.org to ensure conversion of SWC to latest NeuroML2 morphologies

Convert project to use Maven

Bundle with jNeuroML & add -import-swc option

Update org.neuroml.visualiser to accept urls like http://neuromorpho.org/neuroMorpho/dableFiles/jacobs/CNG%20version/146-2-4.CNG.swc & automatically detect that it's SWC, convert to nml2 & visualise

Ask NeuroMorpho.org to add links like:
<a href="http://www.opensourcebrain.org/projects/neuromorpho?explorer=http://neuromorpho.org/neuroMorpho/dableFiles/jacobs/CNG%20version/146-2-4.CNG.swc">View this morphology on Open Source Brain</a>

**Comment by adrianq** [comment]
@tarelli & friends are working on an interpreter for [swc](https://github.com/openworm/org.geppetto.model.swc). I think this is a better approach. Once this is done we can add swc files to the 'OSB 3D Explorer' menu we have in OSB.

**Comment by pgleeson** [comment]
We can put some SWC into https://github.com/OpenSourceBrain/NeuroMorpho to illustrate loading of SWC directly from OSB
